#  Configurations.yaml  ── COPY EXACTLY THIS BLOCK
env:
  width: 400
  height: 200
  peddal_length: 60
  ball_size: 10

  ball_vel_x: 0.025
  ball_vel_y: 0.01

  peddal_thickness: 10
  board_horizontal_padding: 15
